# Generated by Django 2.2 on 2019-08-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClick',
            fields=[
                ('time_stamp', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('stars', models.FloatField()),
                ('username', models.CharField(max_length=50)),
                ('generalCategory', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'user_input',
                'managed': True,
            },
        ),
    ]
