# Generated by Django 2.2 on 2019-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('probability', models.FloatField()),
            ],
            options={
                'db_table': 'heatmap',
                'managed': True,
            },
        ),
    ]
