# Generated by Django 2.2 on 2019-04-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCase',
            fields=[
                ('complaint', models.IntegerField(primary_key=True, serialize=False)),
                ('district', models.IntegerField()),
                ('crime_code', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('street_address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
