# Generated by Django 2.2 on 2019-04-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimecase',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='crimecase',
            table='crime_case',
        ),
    ]
