# Generated by Django 2.2 on 2019-04-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_view', '0003_auto_20190402_0637'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crimecase',
            table='crime_case',
        ),
    ]
