# Generated by Django 2.2 on 2019-07-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=75)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stars', models.FloatField()),
                ('mainCategory', models.CharField(max_length=50)),
                ('generalCategory', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tr_general',
                'managed': True,
            },
        ),
    ]
